### PR TITLE
fix react@15.2.0 Unknown prop warning for draft-js-mention-plugin/MentionSuggestions

### PR DESCRIPTION
**Pull request by mzbac**
fix react@15.2.0 Unknown prop warning
refer to Unknown Prop Warning from draft-js-mention-plugin in react@ 15.2.0 #364

### CODE REVIEW

**Comment by nikgraf** [comment]
thx @mzbac! 🙌

**Comment by zacksiri** [comment]
I just ran into this error, unsure how to fix it. ran `npm update` but still not working

**Comment by nikgraf** [comment]
@zacksiri which version are you using?

**Comment by zacksiri** [comment]
@nikgraf i am using 2.0.0-beta.2

**Comment by nikgraf** [comment]
@zacksiri I think I messed up npm version. If you run npm update it installs `2.0.0-beta1`. Can you double check?

**Pull request merged**
