### PR TITLE
update react peerDependencies

### PR DESCRIPTION
**Pull request by marcoburrometo**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Whether you're fixing a bug or writing a new feature, please open an issue first and discuss with us. We're also reachable on [the draft js slack](https://draftjs.herokuapp.com/)

Briefly describe the use-case/problem you're solving, reference the issue for this bug/feature here

## Implementation

Briefly describe your solution

## Demo

If you're implementing or changing a feature, please add a gif to demo the change, thanks!

### CODE REVIEW

**Comment by marcoburrometo** [comment]
> I would like to remove react 18 from `peerDependencies` as there are some issues reported. Can you adjust your PR?

Hello!
Where can I see these issues? I'm using react 18.2 and everything is working well

**Comment by fxOne** [comment]
#2966

**Comment by marcoburrometo** [comment]
> #2966

I managed to reproduce and solve this. I should be handled well… let me know if there are more issues with react >= 18

**Review by fxOne — APPROVED** [review]

**Comment by marcoburrometo** [comment]
@fxOne Can you please do a release for this?

**Comment by fxOne** [comment]
I will create a new version after I merge #3256.

**Pull request merged**
