### PR TITLE
Toolbar - add link button

### PR DESCRIPTION
**Pull request by Nihaux**
Rebased on master. Add a link button to the toolbar and use an input to get the url.

### CODE REVIEW

**Comment by Nihaux** [comment]
This is what the PR does ATM:
[x] Add Link Button
capture d ecran 2016-10-03 a 17 05 45
[x] Open an input toolbar on click
capture d ecran 2016-10-03 a 17 05 58
[x] insert a link entity on validation
capture d ecran 2016-10-03 a 17 06 14
[x] show a tooltip on link hover
capture d ecran 2016-10-03 a 17 06 31
[x] open the input toolbar with link on tooltip click
capture d ecran 2016-10-03 a 17 06 42

New dependency: [react-portal](https://github.com/tajo/react-portal)

TODO: 
[] correct link validation
[] cleaner css
[] config

The corresponding code lives in [this commit](https://github.com/draft-js-plugins/draft-js-plugins/pull/466/commits/e42b79a8ab4960582b96678309fccc77a2d8f489)

@nikgraf and all let me know what you think :)

**Comment by nikgraf** [comment]
@Nihaux cool stuff, it doesn't let me merge. Will try to rebase the toolbar to master as well and then see if I can merge it.

**Comment by Nihaux** [comment]
Yes I think a rebase on master should resolve most of the conflicts

**Comment by nikgraf** [comment]
It says there are conflicts and won't let me merge with Github. I would say I need to merge master into the toolbar branch and then back to yours to get a mergeable version

**Comment by Nihaux** [comment]
@nikgraf you should rebase https://github.com/draft-js-plugins/draft-js-plugins/tree/toolbar on https://github.com/draft-js-plugins/draft-js-plugins/tree/master and then my branch should be mergeable

**Comment by Nihaux** [comment]
Hum there is indeed a problem, looking into it right now

**Comment by Nihaux** [comment]
Could you rebase and push draft-js-plugins/toolbar with draft-js-plugins/master ? Then I will resolve the conflicts on my branch.

**Comment by Nihaux** [comment]
will rework this based on latest changes on master

**Pull request closed without merging**
