### PR TITLE
Pass through isFocused prop to mention entry

### PR DESCRIPTION
**Pull request by thomas88**
This is a proposal to pass through the `isFocused` prop to the mention entry. This is useful for people who are not using classNames for styling e.g. when using `styled-components`.

Currently I need to do the following in my entry component for determining wether it is focused:

```javascript
  const isFocused = className === theme.mentionSuggestionsEntryFocused;
```

### CODE REVIEW

**Comment by juliankrispel** [comment]
Also @thomas88 thanks for all the contributions recently! Much appreciated <3

**Comment by juliankrispel** [comment]
@thomas88 O_O

**Comment by thomas88** [comment]
@juliankrispel Sorry for the delay, I've been stuck in work at the moment. Will try to add the docs today.

**Comment by juliankrispel** [comment]
@thomas88 thank you :+1:

**Comment by thomas88** [comment]
I've added a reference line in the docs. Please let me know if you'd like me to add something more extensive like showing the attribute in usage.

**Comment by diegohaz** [comment]
Hi, @juliankrispel. Could you please release a new version with this?

**Pull request merged**
