### PR TITLE
[emoji-plugin] add closePopupOnEmojiSelect option

### PR DESCRIPTION
**Pull request by vybu**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

The popup covers up the editor, so we want to close it after user selects an emoji - just like in slack.

## Implementation

Add `closePopupOnEmojiSelect` to config, which simply closes the pupup after emoji has been clicked.

### CODE REVIEW

**Comment by juliankrispel** [comment]
@vybu thanks for the contribution.

Actually it would make more sense imo if the emoji select just closes automatically when a user selects an emoji, like it does in any text editor really. Would you mind just updating the behaviour?

**Comment by vybu** [comment]
Updated PR as per your suggestion to close popup by default.

**Comment by shtetik** [comment]
Hi guys! Thanks for the plugin 👍When will this PR be merge to the master?

**Comment by afurculita** [comment]
Hey @juliankrispel, thanks for the work on the plugins. If this PR is ready, can we have it merged into master?

**Comment by alexfruehwirth** [comment]
Hi, would love to have this merged! 😄 are there any plans when this will be merged?
Thank you! :)

**Comment by afcjunior** [comment]
Can this be merged?

**Comment by sibelius** [comment]
can you rebase?

**Comment by rintala** [comment]
Any update on when this could be merged?

**Comment by fxOne** [comment]
@rintala Feel free to create a PR with this changes as the original creator does not rebase the code. I would love to merge the PR.

**Pull request closed without merging**
