### PR TITLE
Move searchPortal ref function to constructor

### PR DESCRIPTION
**Pull request by feelfreelinux**
## Checklist

- [x] Fix any eslint errors that occur
- [ ] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Fixes issue #666. #667 fixed this issue in mentions plugin. As emoji plugin shares almost the same code, We still need to fix it here.

## Implementation

Moving searchPortal ref function to constructor fixed this issue.

### CODE REVIEW

**Comment by feelfreelinux** [comment]
Not sure if I should update changelog for change that little

**Comment by freedomlang** [comment]
@feelfreelinux Not sure if the emoji plugin still has code almost identical to mention plugin yet.

can not reproduce #666 in online docs about emoji-plugin. ❤️

**Comment by juliankrispel** [comment]
published as `draft-js-emoji-plugin@2.1.1`

**Comment by feelfreelinux** [comment]
@juliankrispel Thanks!

**Pull request merged**
