### PR TITLE
Upgrade to babel 7

### PR DESCRIPTION
**Pull request by TrySound**
In this PR I'm trying to simplify build step.

`babel-plugin-webpack-loaders` is not supported anymore (I'm working
with its author) so I implemented small version of css-modules with only
private classes generation. I think later we could introduce a better
solution for styles without requiring user to inject css files.
`autoprefixer` is bultin in babel plugin.

Babel config for plugins is hoisted to the root.

The prefix in css classes is fixed in a lot of packages.

### CODE REVIEW

**Comment by TrySound** [comment]
Tests are broken in master too. Probably because of some packages has `latest` tag.

/cc @juliankrispel

**Comment by TrySound** [comment]
Friendly ping @juliankrispel

**Comment by juliankrispel** [comment]
hey @TrySound thank you so much, that seem like a good change. Let me fix master, and I'll be in touch shortly

**Comment by TrySound** [comment]
Hey @juliankrispel 
Would you like to continue working on this?

**Pull request closed without merging**
