### PR TITLE
Sidebar position if there is a relative parent

### PR DESCRIPTION
**Pull request by mbutsykin**
## Implementation

New param added.
`createSideToolbarPlugin({relative: true})` to calculate position relatively to editor element

## Demo

So for now parent element can have position relative
image
```
createSideToolbarPlugin({
  theme: { buttonStyles, toolbarStyles, blockTypeSelectStyles },
  relative: true
})
```

## Allow editors for maintainers

- [x] Enable "Allow edits from maintainers" for this PR

### CODE REVIEW

**Comment by mbutsykin** [comment]
@nikgraf please take a look at this

**Comment by juliankrispel** [comment]
@mbutsykin can you elaborate what problem this actually fixes?

**Comment by mbutsykin** [comment]
@juliankrispel sure.

when there is a parent with relative position in DOM, sidebar positioning is wrong.
`top` property counting relatively to scroll position, which obviously will be broken with relative parents.

i added a new flag - `relative` instead of searching like in this [one](https://github.com/draft-js-plugins/draft-js-plugins/pull/629) for performance issues

**Comment by mbutsykin** [comment]
you can reproduce an issue simply adding `postion: relative` to `.editor___3zB6j` element.
in https://www.draft-js-plugins.com/plugin/side-toolbar

**Comment by juliankrispel** [comment]
@mbutsykin just discussed this with @nikgraf earlier this week, we'd rather not add this config option and do it automatically. Is that something you feel up to doing?

**Comment by mbutsykin** [comment]
ok, i'll update PR today or on this weekend, thanks for the feedback

**Comment by mbutsykin** [comment]
@juliankrispel so, will you take a look?

**Comment by Discordius** [comment]
Just mentioning that I am also interested in this PR getting merged.

**Comment by CentaurWarchief** [comment]
Any update?

**Comment by juliankrispel** [comment]
@Discordius @CentaurWarchief @mbutsykin you can actually work around this with just css with a simple transform:

```CSS
transform: 'translate(-100px,-50px) !important;'
```

Or by replacing the Toolbar component with your own implementation.

As discussed above we'd not like to add any more configuration options to this plugin and the workaround seems rather trivial

**Pull request closed without merging**
