### PR TITLE
fixing mention composition

### PR DESCRIPTION
**Pull request by yongningfu**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [ ] Fix any eslint errors that occur
- [ ] Update change-log for every plugin you touch
- [ ] Add/Update tests if you add/change new functionality
- [ ] Add/Update docs if you add/change functionality
- [ ] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Whether you're fixing a bug or writing a new feature, please open an issue first and discuss with us. We're also reachable on [the draft js slack](https://draftjs.herokuapp.com/)

Briefly describe the use-case/problem you're solving, reference the issue for this bug/feature here

## Implementation

in the draftjs  when compositionEnd, it will force re-render, and all the block will unmount, and mount
when useEffect, we will get old state, and using old state to setState, it cause the bug.

https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L242

## Demo

https://user-images.githubusercontent.com/9846613/106443738-d1685300-64b7-11eb-87c0-dd552d6271d3.mov

If you're implementing or changing a feature, please add a gif to demo the change, thanks!

### CODE REVIEW

**Comment by yongningfu** [comment]
another solution is use useLayouyEffect to replace useEffect

**Comment by fxOne** [comment]
Thanks for the PR! 

I tried the `Editor with Mention Plugin` storybook example and notice that with your change the `MentionSuggestion` is no longer opening when I add the trigger. It only opens when I add another character. Can you please check your PR?

**Comment by yongningfu** [comment]
> Thanks for the PR!
> 
> I tried the `Editor with Mention Plugin` storybook example and notice that with your change the `MentionSuggestion` is no longer opening when I add the trigger. It only opens when I add another character. Can you please check your PR?

thanks for you reply,  another solution will be used.

This is the difference between useLayout and useEffect 

useEffect
compositedEnd -> draftJS(restoreEditorDOM) ->  unount Entity -> mount Entity -> draftJS(editor.update(newState)) -> useEffect(setState(oldState)) 

useLayoutEffect
compositedEnd -> draftJS(restoreEditorDOM) ->  unount Entity -> mount Entity -> useLayoutEffect(setState(oldState)) 
-> draftJS(editor.update(newState))

**Comment by yongningfu** [comment]
> > Thanks for the PR!
> > I tried the `Editor with Mention Plugin` storybook example and notice that with your change the `MentionSuggestion` is no longer opening when I add the trigger. It only opens when I add another character. Can you please check your PR?
> 
> thanks for you reply, another solution will be used.
> 
> This is the difference between useLayout and useEffect
> 
> useEffect
> compositedEnd -> draftJS(restoreEditorDOM) -> unount Entity -> mount Entity -> draftJS(editor.update(newState)) -> useEffect(setState(oldState))
> 
> useLayoutEffect
> compositedEnd -> draftJS(restoreEditorDOM) -> unount Entity -> mount Entity -> useLayoutEffect(setState(oldState))
> -> draftJS(editor.update(newState))

@fxOne  hi, this pr is ready for review 😄

**Comment by fxOne** [comment]
Can you please tell me the why we should need `useLayoutEffect` here. I'm aware that this triggers a synchronous re-render. I read [Kent C. Dodds article](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect) about `useLayoutEffect` where he mentions that you need it for 1% of the cases where you need to you need to mutate the DOM and/or do need to perform measurements. So far I haven't seen any issues with the current `useEffect`.

**Comment by yongningfu** [comment]
here is the mini demo, that show the difference between useLayoutEffect and  useEffect. 

You can click each button once, and then the question can be repeated


image

https://codesandbox.io/s/vigilant-babbage-f7ph3?file=/src/App.js

**Comment by yongningfu** [comment]
@fxOne  draftJs onCompositedEnd will unmount all the block entity,  You can check it with the recording screen I provided
https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L242

image

**Comment by fxOne** [comment]
Can you please open an issue first? `useLayoutEffect` will log a warning with SSR can you use [useIsomorphicLayoutEffect](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a) instead?

**Review by sibelius — APPROVED** [review]

**Pull request merged**
