### PR TITLE
migrating counter-plugin

### PR DESCRIPTION
**Pull request by gabrielreisn**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [ ] Fix any eslint errors that occur
- [ ] Update change-log for every plugin you touch
- [ ] Add/Update tests if you add/change new functionality
- [ ] Add/Update docs if you add/change functionality
- [ ] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Whether you're fixing a bug or writing a new feature, please open an issue first and discuss with us. We're also reachable on [the draft js slack](https://draftjs.herokuapp.com/)

Briefly describe the use-case/problem you're solving, reference the issue for this bug/feature here

## Implementation

Briefly describe your solution

## Demo

If you're implementing or changing a feature, please add a gif to demo the change, thanks!

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
It is looking good

Feel free to merge if all tests are pssing

**Comment by sibelius** [comment]
image

some tests are failing

**Comment by gabrielreisn** [comment]
Yeah, i'm aware of that, it was caused by some confusion on mocha/chai trying to run the new tests that now uses jest, so probably I'll need to remove the pattern .spec. and make it as a standard only for jest (I'm open to suggestions)

**Comment by sibelius** [comment]
We can have .spec for mocha and .test for jest or the other way around until we finish the migration

**Comment by gabrielreisn** [comment]
Also, i'd like to use this one to start the typescript migration, you'd mentioned the babel-typescript-plugin. Any other tip for the walkthrough? should I place it on the project root or configure it on each plugin? should I export some specific type for each plugin?

**Comment by sibelius** [comment]
for typescript

we can convert one plugin at a time as well

we can have typescript in the root

and use project references to make sure one plugin can compose from another

https://www.typescriptlang.org/docs/handbook/project-references.html

we can also let typescript check errors on .js files until we finish the migration

we can start being less strict and improve later on

keep pull requests shorter so more people can help with other plugins at the same time

**Comment by sibelius** [comment]
do you need any help with this?

**Comment by gabrielreisn** [comment]
Since i'd take a bit more time on this than expected (couldn't do much on the last week) I'll leave the TS migration on this plugin for later. Can you take a look again before merge @sibelius ?

**Review by sibelius — APPROVED** [review]
We can take a more incremental approach

Do one thing per PR

Tks

**Pull request merged**
