### PR TITLE
Added usage description and removed custom emoji editor

### LINKED ISSUE #113: 'Custom' Emoji editor on website broken
Basically the custom editor on the emoji page looks like this right now if you try autocomplete:

image

### PR DESCRIPTION
**Pull request by juliankrispel**
fixes #113 cc @nikgraf

### CODE REVIEW

**Comment by juliankrispel** [comment]
Fyi the reason why the 'Custom' emoji editor was broken because we're not merging themes with the defaults and the usage on the emoji homepage implied merging, this is what it looked like:
```
const theme = Map({
  emoji: emojiStyles.emoji,
})
```

obviously that's going to break because the theme isn't merged and then you have a ton of undefined theme attributes.

I think merging has value, more about this in #116

**Comment by nikgraf** [comment]
@juliankrispel logo is in there, but not used anywhere?

**Comment by juliankrispel** [comment]
@nikgraf that's a mistake will remove!

**Comment by juliankrispel** [comment]
@nikgraf removed

**Pull request merged**
