### PR TITLE
fix(Editor): allow undefined return for keyBindingFn

### PR DESCRIPTION
**Pull request by ethanve**
Fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/1360

### CODE REVIEW

**Comment by lukesmurray** [comment]
Fixes #1117

**Comment by ethanve** [comment]
@lukesmurray can we merge this in?

**Comment by lukesmurray** [comment]
Yes!

**Comment by ethanve** [comment]
Great! Who has merge access?

**Comment by lukesmurray** [comment]
oh haha i do not. I haven't seen anything merged in this repo for a while but it is open source so it happens! I would use https://www.npmjs.com/package/patch-package if you need these changes asap.

**Pull request merged**
