### PR TITLE
Fix anchor plugin getEditorState undefined issue

### PR DESCRIPTION
**Pull request by iskWang**
Ref. https://codesandbox.io/s/93p6o47wlp

### CODE REVIEW

**Comment by freedomlang** [comment]
@iskWang Not sure if anchor plugin support static-toolbar. I just found that description in online [docs](https://www.draft-js-plugins.com/plugin/anchor)


@juliankrispel Is archor plugin supporsed to support static-toolbar? Or just inline-toolbar?

**Comment by juliankrispel** [comment]
@iskWang first of all thanks for your contrubution! Unfortunately the codepen doesn't work for me I'm afraid

image

If you've made the anchor plugin work with the static toolbar, could you please add a story to the pr for this particular case (or modify an existing one)

Cheers

**Comment by iskWang** [comment]
Thanks @freedomlang  @juliankrispel reply , It's my error screenshot.
And I am not sure how to release "LinkButton" this plugin.
default

P.s: If you comment out [Codesandbox](https://codesandbox.io/s/93p6o47wlp) `linkPlugin.LinkButton` (via line 37) will working.

**Comment by sibelius** [comment]
can you explain more about it?

**Pull request closed without merging**
