### PR TITLE
Mention plugin to aceept '-', '.', '_' while typing

### PR DESCRIPTION
**Pull request by jssisodiyaPG**

### CODE REVIEW

**Comment by nikgraf** [comment]
nice one, can you also update the changelog of the mention plugin?

**Comment by jssisodiyaPG** [comment]
@nikgraf Done 👍

**Comment by jssisodiyaPG** [comment]
@nikgraf thanks for merging the PR. Let me know when you publish this to npm. I will update my package

**Comment by nikgraf** [comment]
@jssisodiyaPG I just tested it an it breaks in Chrome. `.` must be escaped as well. Can you create a second PR with a fix?

**Comment by mzbac** [comment]
@jssisodiyaPG I believe correct regex should be '\._\\-'

**Pull request merged**
