### PR TITLE
Get image path svg as a parameter

### PR DESCRIPTION
**Pull request by Schniz**
to use another caching service/offline

### CODE REVIEW

**Comment by deanshub** [comment]
:+1:

**Comment by nikgraf** [comment]
hey @Schniz, thanks for your contribution. I had this change in mind since a while. Maybe I'm wrong, but the way you implemented it won't help as the `Emoji` is rendered by the plugin.

Can you update the code so the `imagePath` is part of the config. You can move/add the default configuration after this line: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/index.js#L90

**Comment by Schniz** [comment]
@nikgraf done 😄

**Comment by nikgraf** [comment]
Cool thx, I probably change it to `imagePathSvg` and add docs, but you can expect a new release soon 😄

**Comment by nikgraf** [comment]
Just published the new version 1.1.0

**Comment by tanotify** [comment]
Could you please explain is there any way to change icons of such Draft JS Buttons as UnorderedListButton, BoldButton and etc to my custom svg icons

**Pull request merged**
