### PR TITLE
Add tests to Undo Plugin

### PR DESCRIPTION
**Pull request by andrewcoelho**
As per #76  
- [x] RedoButton: button is disabled in case the getRedoStack is empty
- [x] RedoButton: button is not disabled in case the getRedoStack is not empty
- [x] RedoButton: onClick on the button triggers an update with a redo
- [x] UndoButton: button is disabled in case the getRedoStack is empty
- [x] UndoButton: button is not disabled in case the getRedoStack is not empty
- [x] UndoButton: onClick on the button triggers an update with a redo
- [x] plugin config: undoContent
- [x] plugin config: redoContent
- [x] plugin config: theme

Can you clarify a bit what needs to be tested for the plugin config?

### CODE REVIEW

**Comment by mxstbr** [comment]
Thanks so much, the current tests look good!

For the plugin config it'd be amazing to instantiate the plugin with either of those three config options applied, and then checking they changed what they should change. :+1:

**Comment by andrewcoelho** [comment]
Ok, hopefully thats what you guys were looking for. All tests passing now.

**Comment by nikgraf** [comment]
happy to merge @andrewcoelho
for some reason there is a merge conflict. Can you rebase/merge with the latest master?

**Comment by andrewcoelho** [comment]
I have no idea why but if I squash the commits the merge conflict reappears.

**Comment by nikgraf** [comment]
weird, thank for your contribution! interested to do more in the future?

**Comment by andrewcoelho** [comment]
No problem! Yes, this project is very promising. I did some experimenting with Draft.js which you can see at [React text editor](http://www.andrewcoelho.com/react-text-editor/). #49 mentions creating similar functionality as a plugin. I'm adapting my code to make it more pluggable and accessible and hope to submit a PR once I have a good solution. 

If I get some extra spare time I'll try to write more tests for the other plugins as well.

**Comment by nikgraf** [comment]
@andrewcoelho just gave it a try, really nice experience! Would love to see this as a plugin :smile:
btw wanna add this to the list here? https://github.com/nikgraf/awesome-draft-js

also looking forward to see more tests, they were well done and due the amount of work that was involved I got sloppy. Need to catch up with the coverage :smile:

**Pull request merged**
