### PR TITLE
fix: type error on addImage function

### PR DESCRIPTION
**Pull request by sayjeyhi**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [ ] Fix any eslint errors that occur
- [ ] Update change-log for every plugin you touch
- [ ] Add/Update tests if you add/change new functionality
- [ ] Add/Update docs if you add/change functionality
- [ ] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Whether you're fixing a bug or writing a new feature, please open an issue first and discuss with us. We're also reachable on [the draft js slack](https://draftjs.herokuapp.com/)

Briefly describe the use-case/problem you're solving, reference the issue for this bug/feature here

## Implementation

Briefly describe your solution

## Demo

If you're implementing or changing a feature, please add a gif to demo the change, thanks!

### CODE REVIEW

**Comment by sayjeyhi** [comment]
@fxOne please check this as well, there is an issue with types here

**Comment by fxOne** [comment]
The types that you added does not look correct. Can you check them?
Can you also explain what error you want to fix?

**Comment by sayjeyhi** [comment]
`addImage` function has a third parameter to pass additional data when we are adding images, that's why we need to have this feature here, I also added other changes if you want I can share them as well

**Comment by fxOne** [comment]
I think it would be better to just add the `index` to the `addImage` callback as the `handleUpload` and `addImage` are both exposed function. With the `index` you should be able to get your `extraData` and I would guess the information could be usefull for other usecases.

What do you think about that?

**Pull request closed without merging**
