### PR TITLE
Returns array for IE11 compatibilty

### PR DESCRIPTION
**Pull request by dex1t**
fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/266

### CODE REVIEW

**Comment by mjrussell** [comment]
Thanks @dex1t Probably want to do the emoji plugin while you are at it

**Comment by dex1t** [comment]
@mjrussell fixed the emoji plugin 😄  https://github.com/draft-js-plugins/draft-js-plugins/pull/270/commits/055d61b0d5dda9bd02510378deb4c6ceffcb5b70

**Comment by mjrussell** [comment]
@dex1t Thanks! LGTM

**Comment by dex1t** [comment]
thanks for merging ✨

**Comment by dex1t** [comment]
@nikgraf Would you please publish this to npm?

**Comment by nikgraf** [comment]
@dex1t Just cut a new release & published it on npm https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/CHANGELOG.md#102---2016-05-24

**Comment by dex1t** [comment]
Thanks✨

**Pull request merged**
