### PR TITLE
Wysiwyg plugin bundle, feedback and discussion welcome

### PR DESCRIPTION
**Pull request by bkniffler**
**Do not merge, this will probably need some discussion first. Also, I might need to separate them into different PRs, as some are still WIP. This is supposed to be more of a showcase of the current state of work. I've decided to put this into a PR instead of an issue as changes to the code are more clear.**

Hey everybody,
This is a big one. I've tried working on this as separate branches, but it has proved to be much more comfortable to do this on one branch, especially since the plugins are depending on one another. I'm a bit scared about the documentation, examples, etc that will need to be written as soon as everything is done. 

Checkout the new draft-wysiwyg build on top of these plugins:
http://draft-wysiwyg.herokuapp.com/

### Features
- draft-js-alignment-plugin
- draft-js-dnd-plugin
- draft-js-focus-plugin
- draft-js-toolbar-plugin
- draft-js-resizeable-plugin

### Blocks
- draft-js-image-plugin
- draft-js-table-plugin

### Utilities
- draft-js-entity-props-plugin
- draft-js-cleanup-empty-plugin

### CODE REVIEW

**Comment by adrianmc** [comment]
Hey! This is really awesome. I haven't had time to really dive into it yet, but I just wanted to say that I'm 100% down to pitch in and help out with writing documentation, so don't you worry about that!

I'll spend the next few days taking a look at your work!

**Comment by bkniffler** [comment]
Thanks @adrianmc for offering to help! I've just taken the time to cleanup the code, fix linting and add comments to make everything easier to understand.

**Comment by mxstbr** [comment]
Holy guacamoly this is _awesome_!

**Comment by slorber** [comment]
Looks like great work so far.
I'm not really sure what you mean by "wysiwyg plugin bundle" but that looks nice

is your demo page up to date wiith recent updates?

**Pull request merged**
