### PR TITLE
Feature draft js divider plugin

### PR DESCRIPTION
**Pull request by simsim0709**
This divider plugin adds horizontal line(like medium's divider).

I added the story, so you can check that out.

This plugin's repository is originally from https://github.com/simsim0709/draft-js-plugins/tree/master/draft-js-divider-plugin). But, @juliankrispel wanted me to move repository in here.

Its origin repository going to be deprecated, if it's fully merged and published to npm.

I haven't added documentation yet. I will do it when it's acceptable.

### CODE REVIEW

**Comment by juliankrispel** [comment]
lgtm - I like that you can pass the component into config. I'd say go ahead and add some docs and we can merge it :)

**Comment by simsim0709** [comment]
@juliankrispel 

I have added docs and stories for divider plugin.
It now works with focus plugin well, so I have added example how to use divider + focus plugin.

Please, check that out, if it's fine.

**Comment by juliankrispel** [comment]
Legend! 🙌 i‘m afk this weekend but will check asap

**Comment by icarusysuper** [comment]
@simsim0709 It seems that `draft-js-divider-plugin` version1.0.0 not updated? 
I have ran `npm i draft-js-divider-plugin --save` but get the verison0.2.1

**Comment by simsim0709** [comment]
@icarusysuper, could you wait a little bit?
I should talk to @juliankrispel about what's his plan on publishing this package.

@juliankrispel, are you going to rename this package, or you want me to add you as maintainer of this package?

**Comment by icarusysuper** [comment]
@simsim0709 Of course. Thank you!

**Pull request merged**
