### PR TITLE
basic link-plugin

### PR DESCRIPTION
**Pull request by nihaux**
This plugin is meant to provide a base strategy and a base react component to decorate links in draft-js.

Could be used with air-toolbar for instance

### CODE REVIEW

**Comment by mzbac** [comment]
@Nihaux could you tell me what's the purpose of basic link-plugin? we already have the draft-js-linkify-plugin.

**Comment by Nihaux** [comment]
This plugin is meant to centralize the detection and decoration of entity links (entity.type === 'LINKS') whereas the linkify plugin is meant to find and embed portions of text that looks like links (www.google.fr)

**Comment by mzbac** [comment]
@Nihaux  thanks for your explanation

@nikgraf  could you please review this RP.

**Comment by nikgraf** [comment]
@Nihaux looks good to me. Can you add a documentation page for this as well?

**Comment by Nihaux** [comment]
@nikgraf done

**Comment by Nihaux** [comment]
@nikgraf should I close this ?

**Comment by Nihaux** [comment]
hello @nikgraf, i've just rebased this branch. Is there anything blocking this being merge ?

**Comment by Nihaux** [comment]
@nikgraf ?

**Comment by nikgraf** [comment]
@Nihaux will look into it over the next week. Not sure if we might postpone it as first thing right after 2.0. These are high priority features to me right now for shipping 2.0 https://github.com/draft-js-plugins/draft-js-plugins/issues/329

**Comment by jrock17** [comment]
Any chance of getting this conflict resolved and publishing this? I'm having trouble getting entity links to show up in draft-js-plugins. Hoping this can help.

Thanks.

**Comment by nikgraf** [comment]
Since @juliankrispel is putting in way more time we decided to merge the anchor plugin which will replace this PR. Sorry @nihaux for the double work. Let me know if anything is missing in the anchor plugin that you need. Happy to look into it.

**Pull request closed without merging**
