### PR TITLE
add react-portal to emojis and mentions

### PR DESCRIPTION
**Pull request by mattkrick**
## Implementation

In #341 you said you were open to a PR, so here's a minimal example of what is possible when we use a portal to break out of the DOM tree. 

## Demo

Nothing fancy to show, it looks the same!

## Use-case

As you can see in the example, even though the parent div is `position: relative` & `overflow: hidden`, the full menu still shows. This is the same strategy that facebook uses. If we don't make this change, then a designer could very easily bork the entire menu by simply changing the styles of a nearby component. A good summary of this issue (albeit with a different conclusion) is here: https://medium.com/@david.gilbertson/modals-in-react-f6c3ff9f4701. Ideally, we can switch over all plugins that produce a modal.

If closing animations, multiple menus, or more complex logic is required, we could switch to a more complex portal component that I made (https://github.com/mattkrick/react-portal-hoc), but as the name implies that is a higher-order component & I figured I'd start simple.

### NOTE BREAKING CHANGE FOR `popoverComponent`
The current implementation of `popoverComponent` accepts a component _instance_. 
This is troubling for a couple reasons:
- The instance _must_ be an `HTMLElement` (span, div, etc.)  
- The instance _must_ handle the props passed into it & any extra props in future versions will cause a breaking change since they may not be suitable for the element
- the instance _must_ handle `ref` appropriately, otherwise the modal won't appear
- The `ref` is may be stale & set to `null`. This makes portals impossible & was the main reason for fixing it

Reading the history of the feature, I see it's for using material-ui. Unfortunately, as it is currently written, this is about the only 3rd party package it is useful with because most others don't expect a `ref`.
The path to upgrade would look something like this:
```
const popoverComponent = ({popoverRef, children, closePortal, ...props}) => <Paper ref={props.popoverRef} {...props}>{children}</Paper>
```

With that small tweak, it'll work for everybody! (portals included)

### CODE REVIEW

**Comment by nikgraf** [comment]
@mattkrick thanks for investing time and especially starting small! What do you mean by 

> As you can see in the example, even though the parent div is position: relative & overflow: hidden, the full menu still shows.

Can you do a screenshot what problem this solves?

**Comment by mattkrick** [comment]
sure, i'll screenshot what it looks like if portals aren't used, 1 min

**Comment by mattkrick** [comment]
bad

**Comment by nikgraf** [comment]
Hmmm, just tested and for me it looks like this 

screen shot 2017-05-25 at 06 41 39

What browser are you using?

**Comment by mattkrick** [comment]
heh, that's the point :smile: 

To make that screenshot I removed the `Portal` locally & snapped the shot.

If you're on master, you'll need to add `<div style={{ position: 'relative', overflow: 'hidden' }}>` around the Editor.

Either of those will cause the break.

**Comment by nikgraf** [comment]
Ok, so if someone has `position: 'relative', overflow: 'hidden' ` then it wouldn't show up. But why would you want to add these styles if you don't want overflow hidden anyway? Sorry, seems like I'm missing something here :(

**Comment by mattkrick** [comment]
ah! alrighty lemme use a real world example:

I have 2 lanes of todo items.
Each todo item is a card.
Each card should stay in its lane.
So, I use overflow: hidden on the column.

However, the mention menu is a _child_ of one of those cards and a grandchild of the column, and as a  grandchild, it has to obey the rules of its parents (including overflow!).

So, the result is something like this:
screenshot from 2017-05-24 22-32-21

That means if we don't use portals, we have to be _very very careful_ that a parent div does not use `overflow: hidden`. 

Another example might be using this inside a modal.
We want all the contents to stay _inside_ the modal, but it's OK if the menu goes outside.
Lemme know if that makes sense! If not I'll try to come up with another example.

**Comment by nikgraf** [comment]
Ahhh ok, yeah that makes sense. Since the MentionsSuggestion is a Component you could put it into a Portal yourself

```jsx
  render() {
    return (
      <div className={editorStyles.editor} onClick={this.focus}>
        <Editor
          editorState={this.state.editorState}
          onChange={this.onChange}
          plugins={plugins}
          ref={(element) => { this.editor = element; }}
        />
        <Portal>
          <MentionSuggestions
            onSearchChange={this.onSearchChange}
            suggestions={this.state.suggestions}
            onAddMention={this.onAddMention}
          />
        </Portal>
      </div>
    );
  }
```

The benefit here would be that we don't force developers to use a portal. Having something breaking out of the DOM might cause in various setups. Still we should probably recommend it in the docs! In addition we have one dependency less.

What do you think? btw thanks a lot for investing the time to explain it to me.

**Comment by mattkrick** [comment]
that _could_ work, but I would advise against it for 2 reasons:
- if i want a plugin, i just want it to work :smile: that's the beauty of the plugin ecosystem that you created!
- whether the portal is opened or closed is a function of the internal `isActive` state, which is a child of the Portal. So the example above doesn't work because I'd need to write something like `<Portal isOpened={this.state.isActive}>`. Since parents can't manage the state of their children, I'd have no way to manage that state. 

Now, I _could_ just leave the portal open all the time, but that means I open up a portal for every single plugin on every single draftjs instance. for example, i might have 30 draft-js instances with 3 portal-driven plugins. that'd be 90 extra DOM nodes! that doesn't scale well.

**Comment by nikgraf** [comment]
Makes sense. Let's wait with this change for a bit to avoid confusion and we can do a breaking change when Fiber comes out (which supports Portal out of the box … see https://github.com/facebook/react/blob/master/src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js#L272)

**Comment by mattkrick** [comment]
Does that mean this package would have a hard peer dependency on React v16? I'm OK with that, but I know the road to v16 is a long one, so it may take some folks awhile to make the migration.

**Comment by nikgraf** [comment]
Yeah, as soon as React 16 is out I would like to upgrade so we don't block people from upgrading. I hope React 16 is coming sooner than later. Facebook is using it internally already.

**Comment by jimyaghi** [comment]
Is there any more progress on this? I'm using the plugin in a overflow: auto (scrolling) container and i wish the mentions menu would show on top of the container's lower boundary rather than inside the draft editor and cut by the outer container.

image

**Comment by comatory** [comment]
@jimyaghi I'm on react 15.4.2 and to solve this issue I used `react-portal` on version 3.1.0. It works well for most of it (I had to wrap `MentionSuggestions` component in another `<span>` so I could add `className` prop on it to manipulate `z-index` property.

It's not super elegant but it works. I'm kind of 50/50 on this. On one hand, you're bound to bump into this problem sooner or later with any kind of pop-over, on the other hand I can see how authors do not want to add this feature in. Thankfully I was able to solve this with `react-portal`.

I can see two options here:

- add configuration prop to render mentions/dropdowns outside of parent and utilize native `React.createPortal`. So limiting this feature for newer version of React is OK with me (since there is a solution for older versions)
- do not add any configuration but add a solution to this problem to documentation

**Pull request closed without merging**
