### PR TITLE
[mention] allow @-mention of email addresses

### PR DESCRIPTION
**Pull request by strob**
## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [ ] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

The Mention plugin works well for searching names, but currently does not work for searching email addresses. Here's an example from Dropbox Paper showing email-address-based search in the context of an @-mention:

Screen Shot 2021-04-27 at 6 18 17 PM

Happy to discuss in an Issue if this idea is controversial.

## Implementation

I've modified "getSearchTextAt" to support the trigger string appearing within the search string. The previous approach of finding `lastIndexOf('@')` would reset the search in this case, leading to confusing results.

## Demo

I added a new Storybook test case to show this usage:

https://user-images.githubusercontent.com/208551/116331980-bc812000-a785-11eb-9828-d1c8be456c53.mov

### CODE REVIEW

**Comment by fxOne** [comment]
Great PR!

Can you please add some test cases for you changes to `getSearchTextAt`?

**Comment by strob** [comment]
> Great PR!
> 
> Can you please add some test cases for you changes to `getSearchTextAt`?

Thanks for the fast reply, @fxOne! I've added a few tests.

In case it's helpful, I also made [a branch](https://github.com/strob/draft-js-plugins/tree/rm/test-before) where I cherry-picked the tests atop `draft-js-plugins:master` to show the behavior before.

As expected, the email-address tests fail in master:
```
 FAIL  packages/mention/src/__test__/getSearchTestAt.test.ts
  ● getSearchTextAt with triggers within matches › email address trigger

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Object {
    -   "begin": 0,
    +   "begin": 4,
        "end": 14,
    -   "matchingString": "one@example.c",
    +   "matchingString": "example.c",
      }

      33 |     ],
      34 |   ])('%s', (_description, text, position, triggers, result) => {
    > 35 |     expect(getSearchTextAt(text, position, triggers)).toEqual(result);
         |                                                       ^
      36 |   });
      37 | });
      38 |

      at src/__test__/getSearchTestAt.test.ts:35:55

  ● getSearchTextAt with triggers within matches › email address trigger mid-mention

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Object {
    -   "begin": 9,
    +   "begin": 13,
        "end": 23,
    -   "matchingString": "one@example.c",
    +   "matchingString": "example.c",
      }

      33 |     ],
      34 |   ])('%s', (_description, text, position, triggers, result) => {
    > 35 |     expect(getSearchTextAt(text, position, triggers)).toEqual(result);
         |                                                       ^
      36 |   });
      37 | });
      38 |

      at src/__test__/getSearchTestAt.test.ts:35:55
```

...but I also noticed that the trigger-only case ("@") differs from my branch. I believe that my output ("begin": 0) is more coherent than -1, but I may misunderstand the desired semantics:

```
  ● getSearchTextAt with triggers within matches › trigger only

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
    -   "begin": 0,
    +   "begin": -1,
        "end": 0,
        "matchingString": "",
      }

      33 |     ],
      34 |   ])('%s', (_description, text, position, triggers, result) => {
    > 35 |     expect(getSearchTextAt(text, position, triggers)).toEqual(result);
         |                                                       ^
      36 |   });
      37 | });
      38 |

      at src/__test__/getSearchTestAt.test.ts:35:55
```

**Comment by fxOne** [comment]
You got the wrong file, there is already one there: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/mention/src/utils/__test__/getSearchTextAt.test.ts

**Comment by strob** [comment]
> You got the wrong file, there is already one there: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/mention/src/utils/__test__/getSearchTextAt.test.ts

Whoops! Didn't see that. Updated.

Also, I realized that the "trigger only" test before didn't make sense because the `position` index preceded the entry.

**Comment by fxOne** [comment]
I just checked the changes locally and they looks great! 

There's one little thing that you can change to make it perfect: You cannot see the email address in your new storybook example after you typed the trigger. Maybe it would be better to remove some entries or move it in the list up.

**Pull request merged**
