### PR TITLE
use getEditorState and setEditorState from the store in the EmojiSuggestionsPortal component

### PR DESCRIPTION
**Pull request by dieterwalckiers**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/1234
The problem: The EmojiSuggestionsPortal component tries to access the setEditorState and getEditorState from `this.props`, but these functions are not reliably there.

## Implementation

These functions are always available in `this.props.store` of that component. So my fix is to take them from there. Analog to how the EmojiSuggestions component does it.

### CODE REVIEW

**Review by sibelius — APPROVED** [review]

**Comment by fxOne** [comment]
Can you please fix the tests, I think a rebase with master should fix them.

**Comment by dieterwalckiers** [comment]
@fxOne I rebased with master on my forked version, but now I see changes in this PR that I didn't introduce.
So I guess I messed something up. Shall I just re-fork and open a new PR?

**Comment by fxOne** [comment]
As this is an easy change it might be better to create a new PR.

**Comment by dieterwalckiers** [comment]
@fxOne Ok, created a new one here:
https://github.com/draft-js-plugins/draft-js-plugins/pull/1596

**Pull request closed without merging**
