### PR TITLE
Solving the multi instances issues by adding optional uniqueId

### PR DESCRIPTION
**Pull request by AnasTawfeek**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [ ] Fix any eslint errors that occur
- [ ] Update change-log for every plugin you touch
- [ ] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Multiple instances of the plugins in multiple Editors will conflict and the solution is to create new instance of the plugin for each Editor instance, but if the Editor is wrapped in reusable component, such solution won't be valid, instead, we will create uniqueId for each instance via some uuid generator and validate it before updating the state.

## Implementation

Adding uniqueId to the props that Editor accept and return it from getPluginMethods via getUniqueId.

## Demo
```
...
const uniqueId = 'SomeUniqueId'; // maybe using the uuid package
class MyComponent extends Component{
  ...
    handleChange(editorState, pluginsMethods){
        if(pluginsMethods.getUniqueId() === uniqueId){
            this.setState({editorState});
        }
    }
  ...
    render(){
        return (
               <Editor
                    editorState={editorState}
                    onChange={(editorState, pluginsMethods) => handleChange(editorState, pluginsMethods)}
                    plugins={plugins}
                    uniqueId={uniqueId}
                />
        )
    }
  ...
}
...
```

### CODE REVIEW

**Comment by juliankrispel** [comment]
Hey @AnasTawfeek, thanks for the pr.

I don't see how this solves the problem since plugins often contain state (it's considered a design flaw but that's how it works).

I'm closing this pr since I'm not sure what it can add to the project in this state. Feel free to disagree, I'd be happy to reopen it if there's good reason and explanation. I'm also available for chats on the draft js slack, feel free to hit me up there

**Comment by juliankrispel** [comment]
@meteorplus @anastawfeek feel free to hit me up on the draft js slack. I‘m fairly certain that we can fix this without this change

**Comment by laurids-reichardt** [comment]
@juliankrispel @AnasTawfeek  @x5engine I'm having the same issue. Did you find a solution to the problem?

**Comment by nabeelnazirvf** [comment]
@juliankrispel I am facing the same issue. Check my `DraftEditor.js` custom component. Each time I have to add a new editor along with new plugins. Is there a way that I can use the rich text editing with dynamically created text areas (multiple text areas)?

Code:
```import React, { Component } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import Editor from 'draft-js-plugins-editor';
import createLinkPlugin from 'draft-js-anchor-plugin';
import createInlineToolbarPlugin from 'draft-js-inline-toolbar-plugin';
import draftDefaultStyles from './DraftDefault.css';
import editorStyles from './DraftEditor.css';
import buttonStyles from './buttonStyles.css';
import toolbarStyles from './toolbarStyles.css';
import linkStyles from './linkStyles.css';

import ss from 'draft-js-inline-toolbar-plugin/lib/plugin.css';
import { convertToRaw, EditorState } from 'draft-js';
import { stateToHTML } from 'draft-js-export-html';
import { stateFromHTML } from 'draft-js-import-html';
import { UnorderedListButton, OrderedListButton } from 'draft-js-buttons';
import customBranding from '../../../../hoc/customBranding/customBranding';

import { connect } from 'react-redux';
import { compose } from 'redux';
import { withCookies } from 'react-cookie';

const inlineToolbarPlugin1 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
const inlineToolbarPlugin2 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
const inlineToolbarPlugin3 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
const inlineToolbarPlugin4 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
const inlineToolbarPlugin5 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
const inlineToolbarPlugin6 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
const inlineToolbarPlugin7 = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});

const InlineToolbar1 = inlineToolbarPlugin1.InlineToolbar;
const InlineToolbar2 = inlineToolbarPlugin2.InlineToolbar;
const InlineToolbar3 = inlineToolbarPlugin3.InlineToolbar;
const InlineToolbar4 = inlineToolbarPlugin4.InlineToolbar;
const InlineToolbar5 = inlineToolbarPlugin5.InlineToolbar;
const InlineToolbar6 = inlineToolbarPlugin6.InlineToolbar;
const InlineToolbar7 = inlineToolbarPlugin7.InlineToolbar;

const linkPlugin1 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});
const linkPlugin2 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});
const linkPlugin3 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});
const linkPlugin4 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});
const linkPlugin5 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});
const linkPlugin6 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});
const linkPlugin7 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});

const plugins1 = [inlineToolbarPlugin1, linkPlugin1];
const plugins2 = [inlineToolbarPlugin2, linkPlugin2];
const plugins3 = [inlineToolbarPlugin3, linkPlugin3];
const plugins4 = [inlineToolbarPlugin4, linkPlugin4];
const plugins5 = [inlineToolbarPlugin5, linkPlugin5];
const plugins6 = [inlineToolbarPlugin6, linkPlugin6];
const plugins7 = [inlineToolbarPlugin7, linkPlugin7];

@customBranding
class DraftEditor extends Component {
  constructor(props) {
    super(props);
    const contentState = stateFromHTML(props.description);
    this.state = {
      editorState: EditorState.createWithContent(contentState),
    };
    this.onChange = this.onChange.bind(this);
  }

  onChange(editorState) {
    this.setState({
      editorState,
    });
    const content = editorState.getCurrentContent();
    const dataToSaveBackend = convertToRaw(content);
    let options = {
      entityStyleFn: entity => {
        const entityType = entity.get('type').toLowerCase();
        if (entityType === 'link') {
          const data = entity.getData();
          return {
            element: 'a',
            attributes: {
              href: data.url,
              target: '_blank',
            },
            style: {
              // Put styles here...
            },
          };
        }
      },
    };
    this.props.descriptionEditChild({
      target: { value: stateToHTML(content, options) },
    });
  }

  focus = () => {
    this.editor.focus();
  };

  cssSwitch = param => {
    switch (param) {
      case 'description':
        return editorStyles.newDescriptionInput;
      case 'eligibility':
        return editorStyles.newEligibility;
      case 'scholarship':
        return editorStyles.newScholarship;
      case 'subDescription':
        return editorStyles.newSubDescriptionInput;
      case 'activities':
        return editorStyles.newActivitiesAndAdmin;
      case 'excursions':
        return editorStyles.newActivitiesAndAdmin;
      case 'addOns':
        return editorStyles.newActivitiesAndAdmin;
      default:
        return editorStyles.newDescriptionInput;
    }
  };

  placeholderSwitch = (param, alias_program) => {
    switch (param) {
      case 'description':
        return `${alias_program} intro...`;
      case 'eligibility':
        return `Enter any eligibility requirements for the ${alias_program}...`;
      case 'scholarship':
        return `Enter any scholarship information for the ${alias_program}...`;
      case 'subDescription':
        return `${alias_program} Description...`;
      case 'activities':
        return null;
      case 'excursions':
        return null;
      case 'addOns':
        return null;
      default:
        return editorStyles.newDescriptionInput;
    }
  };

  pluginsSwitch = param => {
    switch (param) {
      case 'description':
        return plugins1;
      case 'eligibility':
        return plugins2;
      case 'scholarship':
        return plugins3;
      case 'subDescription':
        return plugins4;
      case 'activities':
        return plugins5;
      case 'excursions':
        return plugins6;
      case 'addOns':
        return plugins7;
      default:
        return editorStyles.newDescriptionInput;
    }
  };

  render() {
    const { status } = this.props;
    const alias_program = this.props.alias_program
      ? this.props.alias_program
      : 'Program';
    return (
      <div className={this.cssSwitch(status)} onClick={this.focus}>
        {status === 'description' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={this.pluginsSwitch(status)}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar1>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin1.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar1>
          </div>
        )}
        {status === 'eligibility' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={this.pluginsSwitch(status)}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar2>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin2.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar2>
          </div>
        )}
        {status === 'scholarship' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={this.pluginsSwitch(status)}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar3>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin3.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar3>
          </div>
        )}
        {status === 'subDescription' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={plugins4}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar4>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin4.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar4>
          </div>
        )}
        {status === 'activities' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={plugins5}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar5>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin5.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar5>
          </div>
        )}
        {status === 'excursions' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={plugins6}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar6>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin6.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar6>
          </div>
        )}
        {status === 'addOns' && (
          <div>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={plugins7}
              ref={element => {
                this.editor = element;
              }}
              placeholder={this.placeholderSwitch(status, alias_program)}
            />
            <InlineToolbar7>
              {externalProps => (
                <div>
                  <UnorderedListButton {...externalProps} />
                  <OrderedListButton {...externalProps} />
                  <linkPlugin7.LinkButton {...externalProps} />
                </div>
              )}
            </InlineToolbar7>
          </div>
        )}
      </div>
    );
  }
}

const mapStateToProps = state => ({
  customBranding: state.profile.customBranding || {},
});

export default compose(
  withCookies,
  withStyles(
    draftDefaultStyles,
    ss,
    editorStyles,
    buttonStyles,
    toolbarStyles,
    linkStyles,
  ),
  connect(
    mapStateToProps,
    null,
  ),
)(DraftEditor);
```

I called this component like this:
```
<DraftEditor
                description={this.props.eligibility}
                descriptionEditChild={this.props.eligibilityEdit}
                status={'eligibility'}
                disabled={this.props.showEligibility == true ? false : true}
                alias_program = {this.props.alias_program}
              /> 
```

**Comment by vdesdoigts** [comment]
Hello, did you find a solution ?

**Comment by sibelius** [comment]
you need to create plugins on render using `useMemo`

**Comment by vdesdoigts** [comment]
Yep thanks!

**Pull request closed without merging**
