### PR TITLE
Adding ability to set prefix and target for Linkify plugin

### PR DESCRIPTION
**Pull request by adrianmc**
Closes this issue: #174

### CODE REVIEW

**Comment by adrianmc** [comment]
Uh oh, it seems that the Travis build has failed because I used the ES2015 startsWith() function.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

I thought that Babel will compile down automatically?

**Comment by nikgraf** [comment]
While we use babel to compile the code it is shipped to npm as ES5 code. People might not use babel-polyfills and as a library creator you don't want to prescribe them to it. Can you change it to use `indexOf`? Sorry, didn't see it before.

One more thing that is not necessary, but would make my life a lot easier is to add the new params to the docs here and even extend the CustomLinkifyPlugin to use target blank (it's a great example): https://github.com/draft-js-plugins/draft-js-plugins/tree/master/docs/client/components/pages/Linkify

Updating the Changelog in the plugin would be nice as well :smile: 

Also not necessary, but would be really cool is adding tests for it. That said the test coverage is pretty low except for the plugin editor. I'm aiming to improve it. In any way, I will merge it once the indexOf is change. Let me know if you want to do more.

**Comment by adrianmc** [comment]
No worries, great suggestions. I'll get on those changes. I'll probably have it done in a day or so.

As for tests, I'm still pretty green to testing. Do you have any recommendations for how I should approach this? Should I just follow the same pattern in the existing tests file for the Link component?

**Comment by adrianmc** [comment]
@nikgraf Several things:

1. I've replaced the prefix functionality with Linkify's own intelligent url mode. Previously, if we had `google.com` and `ftp://google.com` we would get hrefs like `http://google.com` and `http://ftp://google.com` respectively.

  Use of `IndexOf()` or `startsWith()` is no longer necessary.

  That's obviously bad, but by using Linkify's own methods, the result is now what the user expects (`http://google.com` and `ftp://google.com`).

  I've written tests for this, you can take a look. I also don't believe this requires specific documentation since it is the natural behaviour of the Linkify It library (https://github.com/markdown-it/linkify-it).

2. I have added the `_blank` example to CustomLinkifyEditor as you have requested. Please take a look.

3. I've updated the CHANGELOG as requested.

4. I added a bunch of tests that I think show the benefits of using the Linkify module's prefix functionality. Take a look to see if you think they are sufficient.

**Comment by nikgraf** [comment]
This is soooo good! Thanks @adrianmc

**Comment by nikgraf** [comment]
@adrianmc you changes are live on https://www.draft-js-plugins.com

I'm planning on cutting 1.0.0 of the linkify plugin mid/end this week.

**Comment by adrianmc** [comment]
Awesome! Let me see what else I can help out with.

**Pull request merged**
