### PR TITLE
Fixed up arrow not looping

### PR DESCRIPTION
**Pull request by stevensacks**
This fixes issue #437.

### CODE REVIEW

**Comment by mzbac** [comment]
Hi @stevensacks I am getting "Uncaught TypeError: Cannot read property 'size' of undefined" error. could you please fix the error. than I can merge your PR.. thank you

**Comment by stevensacks** [comment]
It's a typo.

**Comment by stevensacks** [comment]
I fixed the typo. Sorry about that!

**Comment by nikgraf** [comment]
@stevensacks could you also create a PR with a Changelog update?

@mzbac thx for reviewing. let's make sure we include changelog updates. It's hard to track them afterwards :)

**Pull request merged**
