### PR TITLE
Feat: Emoji picker menu position Alignment  ( top/buttom )

### PR DESCRIPTION
**Pull request by rohanvachheta**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem
The Menu for the Emoji picker was situated at the End of the parent, where for some cases we do require that position to be on top so we've provided one prop based on the position for menu 

## Implementation

Here I've provided external prop for the Emoji picker which will be indecating the position for the menu 
where defualt position is bottom which is same as below, if we provide props as "top" it will be align on top

## Demo

we need to provide this props in the Emoji select if we want to show Emojij menu items on tha top

` <EmojiSelect menuPosition="top" closeOnEmojiSelect />`

### CODE REVIEW

**Comment by fxOne** [comment]
I like the idea for the PR. 

Can you change your implementation to `popper.js` as this would give us more options and should simplify the code? You can see in this PR https://github.com/draft-js-plugins/draft-js-plugins/pull/2212 an implementation I have already done for an other plugin.

**Comment by rohanvachheta** [comment]
@fxOne  here I've added just Emoji Header button position not the whole Emoji picker position where it can be shown from top or bottom , ex: 
image

**Comment by fxOne** [comment]
Ah, I understand now :)

If you could add you changes to the changelog and to the documentation I would love to merge this PR!

**Comment by rohanvachheta** [comment]
@fxOne  yes added change log here https://github.com/draft-js-plugins/draft-js-plugins/pull/2433/commits/fa9a7bbc71282bbe802b6109cb9fe2950da2fe07

**Review by fxOne — APPROVED** [review]

**Pull request merged**
