### PR TITLE
Toggle side toolbar on click

### PR DESCRIPTION
**Pull request by StevenIseki**
Toggle side toolbar on click

### CODE REVIEW

**Comment by StevenIseki** [comment]
draft-plugins-click

**Comment by StevenIseki** [comment]
Issues still to look at - 
- The clicking of the menu, is this better than on hover, my opinion it is and is a more common action, or do we want both and an option can be passed to the side-toolbar hover or click.
- The menu needs to hide when clicking back into the editor, currently a bug, should be fixable.

We need to publish a new version of the buttons with this, In `DefaultBlockTypeSelect/index.js` I updated the buttons import to `from '../../../../draft-js-buttons/src/';` so it will work but this will have to change back

**Comment by StevenIseki** [comment]
Just a note, this functionality is now present in the draft-js-sidebar-plugin in https://github.com/vacenz/last-draft-js-plugins so this pr can be closed if required.

**Comment by nikgraf** [comment]
Definitely check out https://github.com/vacenz/last-draft-js-plugins!

**Pull request closed without merging**
