### PR TITLE
Add a check for a null entity and return null

### PR DESCRIPTION
**Pull request by MattyBalaam**
This follows a pattern used by other plugins such as draft-js-image-plugin.

See issue: https://github.com/draft-js-plugins/draft-js-plugins/issues/1122

### CODE REVIEW

**Comment by freedomlang** [comment]
@MattyBalaam mind adding to the changelog?

**Comment by gnestor** [comment]
I just ran into this issue!! Thanks @MattyBalaam!

**Comment by MattyBalaam** [comment]
I don’t have permissions to merge.

**Comment by freedomlang** [comment]
@welliam Sorry to hear that! Currently, maintainers is focusing on `next`. Maybe you can pin @juliankrispel in the channel #draft-js-plugin of DraftJS Slack [organization](https://draftjs.herokuapp.com/).

@MattyBalaam Btw, mind bump the version to `2.0.2` and update the changelog  like this [`one`](https://github.com/draft-js-plugins/draft-js-plugins/blob/9975f41d7f0533843882e5bf4e483081c17f7d12/draft-js-image-plugin/CHANGELOG.md)?

**Comment by welliam** [comment]
:+1: thanks for the swift responses! @freedomlang i'll look into that today

**Comment by welliam** [comment]
:+1: thanks for the swift responses! @freedomlang i'll look into that today

**Pull request merged**
