### PR TITLE
add Chinese support in mention plugin

### PR DESCRIPTION
**Pull request by mzbac**
refer to https://github.com/draft-js-plugins/draft-js-plugins/issues/419

### CODE REVIEW

**Comment by nikgraf** [comment]
@mzbac you rock! interested to become a core-contributor of draft-js-plugins?

**Comment by nikgraf** [comment]
updated the changelog https://github.com/draft-js-plugins/draft-js-plugins/pull/426

**Comment by mzbac** [comment]
@nikgraf  Currently I am developing a product heavily relay on draft-js-plugins, so really would love to be a core-contributor and contribute more.

**Comment by nikgraf** [comment]
@mzbac alright, I'm sending you an invite to the Github Organization. Can you create a PR for the public website?

If you want to we can do a call sometime next week to chat a bit. Would be cool to see what you are working on & I can share my ideas for future development. 😄

**Comment by mzbac** [comment]
@nikgraf  Sorry, can you tell me more about the PR for the public website? didn't quite understand what's that about..

**Comment by nikgraf** [comment]
@mzbac there is a Team section on the website. Wanna be added there?

**Comment by mzbac** [comment]
@nikgraf no need at the moment, but I do notice that on that website we got some errors which cause some page doesn't work properly. e.g.Sticker..  it seems its build code is different than current master branch. is there anything that I can do to help fixing it?

**Comment by nikgraf** [comment]
@mzbac yeah, my original plan was to keep 1.x on the website until 2.x is done, but @adrianmc deployed without knowing that. I will redeploy later today with the beta after fixing all stuff I find.

This is my list for today:

- upgrade all packages & fix linting <-- doing right now
- fix max stoiber image
- fix emoji plugin
- add japanese char support
- fix data (initial state) for unicorn editor

- test everything works
- deploy docs v2 (add beta note)
- cut the v2 beta 3 release
- deploy docs v1
- add note for docs v1 to docs v2
- setup weekly meeting for draftjs contributors

If you have time to look into emoji autocompletion that would be great. The images are broken (I recently merged a PR and missed this).

For Japanese character support I found this: https://gist.github.com/ryanmcgrath/982242#file-japaneseregex-js-L14 & https://gist.github.com/terrancesnyder/1345094#file-regex-japanese-txt-L1-L2

**Comment by nikgraf** [comment]
Let me know if you have time to pick on of these tasks …

**Comment by mzbac** [comment]
@nikgraf  I would like to work on emoji autocompletion, can you refer me to the related issue?  for the Japanese issue, if we can find someone who can typing Japanese will be great for us to test our implementation..

**Comment by nikgraf** [comment]
@mzbac I just reverted back to the old emoji list as it was broken, see more details here: https://github.com/draft-js-plugins/draft-js-plugins/pull/405

**Comment by nikgraf** [comment]
@mzbac what would be quite interesting is providing documentation pages for the table plugin

**Comment by mzbac** [comment]
@nikgraf I am not good at writing docs.. not a native English speaker..but I could help on writing some demonstration codes I guess..

**Comment by nikgraf** [comment]
@mzbac that would be great already

**Pull request merged**
