### PR TITLE
Fix code of heart emoji

### PR DESCRIPTION
**Pull request by steven-qi**
## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Emoji `:heart:` in priority list won't be displayed correctly (see #925 ).

## Implementation

Fix the incorrect Unicode code of `:heart:`.

## Demo

image

### CODE REVIEW

**Comment by steven-qi** [comment]
@nikgraf I saw that you are the original author of this file. Could you please review this change, as I don't know whether the incorrect Unicode was made intentionally or not.

**Comment by juliankrispel** [comment]
Hi @steven-qi I've addressed your issue #925 - I can't reproduce the bug I'm afraid.

There are two unicodes here, the first one means red-heart, the second is just heart (with default color). I'm not sure of the original intentions but it seems to work fine for me.

`['2764-fe0f', '2764']`

**Comment by steven-qi** [comment]
@juliankrispel I guess this could be a platfom-specific issue, as I am using Windows 10 + Chrome. I can easily reproduce it on the demo page.

https://www.draft-js-plugins.com/plugin/emoji

image

I do realized that simply replace it with 2764 will cause a black heart be rendered, and I am using `:heartbeat: 1f493` instead in priority list of my own project.

**Comment by steven-qi** [comment]
BTW, `2764-fe0f` doesn't seems to be one unicode but two.

Here is what I found from emojione repo regarding how `-` is handled...

https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L409

I guess that this PR can be closed now, and a true fix is needed.

**Comment by steven-qi** [comment]
I might have figured out the root cause of this issue.

The svg file for [2764](https://cdn.jsdelivr.net/emojione/assets/svg/2764.svg?v=2.2.7) missing width/height, thus won't be rendered as background. Specifying a `width: 1em` would fix it.

I will update this PR soon.

**Comment by juliankrispel** [comment]
merged finally thank you so much ❤️

**Comment by steven-qi** [comment]
Thanks @juliankrispel for merging. It is great that we get the broken ❤️ fixed. 😄

**Comment by juliankrispel** [comment]
❤️👌😂

**Pull request merged**
