### PR TITLE
[Mention Plugin] Do not render popover if there are no mentions

### LINKED ISSUE #2049: Bug in mention plugin - popover/popper.
## Environment

It happens everywhere, even on official website. 

- @draft-js-plugins/editor version: current
- plugin name and version: current

## Description

The issue appears to trigger when have more than one mention. For example of there is Matthew Russel and type @ and mouse is focused on at least one suggestion from suggestions list, deleting @ with backspace leaves empty popper artifact that can be discarded only after the page reload.

### PR DESCRIPTION
**Pull request by fxOne**
## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

closes #2049

## Implementation

Do not render component if there are no mentions to show. @felippepuhle can you please have a look at it if it might break anything in relation with #1696

### CODE REVIEW

**Comment by felippepuhle** [comment]
@fxOne we have an use case where we want to show a message if we have empty results... how we'd handle this case? Maybe if we'd have a new 'emptyComponent' prop or something like that?

**Comment by fxOne** [comment]
@felippepuhle As you would like to show the `emptyComponent` inside the popup it wont change anything. I guess have to look for an other solution :)

**Comment by fxOne** [comment]
@felippepuhle would it be OK if I add a `renderEmptyPopup` prop which is by default `false`? In your case you can set it to true and show the empty message component.

**Comment by felippepuhle** [comment]
@fxOne I just checked and we're using `popoverComponent`, so I think we wouldn't be affected by this change

**Pull request merged**
