### PR TITLE
Support paste image

### PR DESCRIPTION
**Pull request by whitejava**

### CODE REVIEW

**Comment by whitejava** [comment]
Oh, there is a lint problem, I'll fix later.

**Comment by nikgraf** [comment]
This is pretty cool! People might paste in other media formats and other plugins might capture that. Can you remove the console.error statements and just return.

**Comment by whitejava** [comment]
I made it.

**Comment by nikgraf** [comment]
@whitejava I looked into the current implementation of the image plugin and it wasn't even using Atomic blocks. I was refactoring it in a branch to Atomic blocks. I hope to push & merge this soon and then we can apply your change to the new stuff.

**Comment by whitejava** [comment]
I'm not sure what is Atomic blocks.
What is the problem?
What should I do next?

**Comment by mzbac** [comment]
@whitejava I think in you PR you are inserting atomic block which has block type 'atomic', but in you blockrenderFn you are checking block type 'block-image'

**Comment by whitejava** [comment]
how to do...

**Comment by the1sky** [comment]
when support paste image? thanks

**Comment by juliankrispel** [comment]
@whitejava we'd like to keep the image plugin functionality simple. But it'd be interesting to have a handle paste plugin which could handle use-cases like this, ping me on the draft-js slack if you want to talk about this!

**Comment by lcc19941214** [comment]
I don't know whether you have solved it. Here is my way to paste image to editor.

At first add a paste event handler to document and let editor to record the focus state.
```javascript
import { pasteAndUploadImage } from './imageUtil';
...
document.addEventListener('paste', this.handleOnPaste, false);

handleOnPaste = e => {
  if (this.isFocus) {
    pasteAndUploadImage(e, this.handleOnPasteAndUploadImage)
    this.props.onPaste(e);
  }
};
...
<Editor onFocus={() => this.isFocus = true} onBlur={() => this.isFocus = false} />
```

Then use the methods from imageUtil to insert image.
```javascript
// imageUtil.js
import { EditorState, AtomicBlockUtils } from 'draft-js';
import axios from 'axios';
import * as EntityType from '../constants/entity';

const imageURLKeyMap = {};

export const addImage = (editorState, url, extraData) => {
  const contentState = editorState.getCurrentContent();
  const contentStateWithEntity = contentState.createEntity(
    EntityType.IMAGE,
    'IMMUTABLE',
    { ...extraData, src: url }
  );
  const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
  imageURLKeyMap[url] = entityKey;
  const newEditorState = AtomicBlockUtils.insertAtomicBlock(editorState, entityKey, ' ');
  return newEditorState;
};

export const updateImage = (editorState, toMergeData, localURL) => {
  const contentState = editorState.getCurrentContent();
  const entityKey = imageURLKeyMap[localURL];
  const nextContentState = contentState.mergeEntityData(entityKey, toMergeData);
  delete imageURLKeyMap[localURL];
  return EditorState.push(editorState, nextContentState);
};

export const uploadImage = (url, file, config = {}) => {
  const data = new FormData();
  data.append('file', file);
  return axios
    .post(url, data, config)
    .then(res => {
      return res;
    })
    .catch(console.error);
};

// here is the paste method
export const pasteAndUploadImage = (event, onload) => {
  const items = (event.clipboardData || event.originalEvent.clipboardData).items;
  for (let item of items) {
    if (item.kind === 'file' && item.type.includes('image/')) {
      const blob = item.getAsFile();
      const reader = new FileReader();
      reader.onload = e => onload(blob, e);
      reader.readAsDataURL(blob);
    }
  }
};
```

It works well with paste screen shots, however, when you copy a image file from your computer, it will **at first paste the file name** and then the image.

That seems I need to spend some time to handle those file names. had somebody already solved this? Thx.

**Comment by QuietWind** [comment]
Add my resolve problem anwser：

first : source code position [handlePastedFiles](https://github.com/facebook/draft-js/blob/8c3dd86bd1cd7c5fc0201912404312324c150b57/src/component/handlers/edit/editOnPaste.js#L49)

second: editor you can add customer handler 

see commit:
https://github.com/QuietWind/qtext/commit/585b78e985762b9f428eeb4ddb065255361af420#diff-93bc859637a9b7854dd52f54137379c9


hope to be able to help you.

**Pull request closed without merging**
