### PR TITLE
Add draft-js-katex-plugin

### PR DESCRIPTION
**Pull request by letranloc**
Add `katex` plugin to `draft-js-plugins`, using [katex](https://github.com/Khan/KaTeX) to render, modified from [Tex example](https://github.com/facebook/draft-js/tree/master/examples/draft-0-10-0/tex).

### CODE REVIEW

**Comment by nikgraf** [comment]
@letranloc this looks really cool. Would you mind release it as a separate plugin. It can live under your name or if you want to I can create a repository in this organization. In both cases we can add it here: https://github.com/draft-js-plugins/draft-js-plugins#built-by-the-community

Right now maintaining all the plugins is already a lot of work and adding more would be too much burden for me.

**Comment by stevewillard** [comment]
This is a great looking plugin! Thanks for putting this together @letranloc

**Comment by letranloc** [comment]
I have created new repo for this plugin at [letranloc/draft-js-katex-plugin](https://github.com/letranloc/draft-js-katex-plugin). Please review to make sure I don't make any mistakes. Thanks! 😇

**Comment by nikgraf** [comment]
@letranloc looks awesome, I don't have time for an in depth review, but maybe someone wants to jump in?

I added it here:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/README.md#built-by-the-community
&
https://github.com/nikgraf/awesome-draft-js#plugins-and-decorators-built-for-draftjs

**Pull request closed without merging**
