### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by nikgraf**
What do you think? @juliankrispel @okonet @bkniffler @mxstbr

### CODE REVIEW

**Comment by mxstbr** [comment]
I like it!

**Comment by mxstbr** [comment]
I've merged for now, let's iterate on this with PRs if needed!

**Comment by nikgraf** [comment]
@mxstbr wow, did you use on of the new merge features?

P.S. please never again, it screwed with my local history

**Comment by mxstbr** [comment]
Hahaha yeah I did, sorry! I wanted to try it, won't do it again!

**Comment by nikgraf** [comment]
hehe, no worries. Just go really confused, because I couldn't find my changes in the history, but I saw it was merged according to Github

**Comment by okonet** [comment]
:+1:

**Pull request merged**
