### PR TITLE
add onOpen and onClose callback props to EmojiSelect

### LINKED ISSUE #1580: Can 'draft-js-emoji-plugin' has onOpen, onClose callback for EmojiSelect Plugin ?
Can 'draft-js-emoji-plugin' has onOpen, onClose callback for EmojiSelect Plugin ?

### PR DESCRIPTION
**Pull request by murattishkul**
Please check out Contributing Guidelines. By following this template you help us to review your code.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md

## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [ ] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

Whether you're fixing a bug or writing a new feature, please open an issue first and discuss with us. We're also reachable on [the draft js slack](https://draftjs.herokuapp.com/)

Briefly describe the use-case/problem you're solving, reference the issue for this bug/feature here

This one closes #1580
Some users desired onOpen and onClose props to be thrown to EmojiSelect

## Implementation

Briefly describe your solution

added callback props to be called upon closing and opening of the popover

## Demo

If you're implementing or changing a feature, please add a gif to demo the change, thanks!

### CODE REVIEW

**Comment by fxOne** [comment]
Thanks for the PR!

Can you please add you change also to the documentation for the homepage? You can find the file here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/docs/pages/plugin/emoji/index.js

**Comment by murattishkul** [comment]
Thank you @fxOne , I updated it

**Review by fxOne — APPROVED** [review]

**Comment by nugmanoff** [comment]
@murattishkul good job! thanks for this one

**Comment by murattishkul** [comment]
@fxOne when is the next release for emoji plugin draft js? I look forward to use this pr at my job

**Comment by fxOne** [comment]
@murattishkul I just created a new release for you: https://www.npmjs.com/package/@draft-js-plugins/emoji

**Comment by murattishkul** [comment]
thank you @fxOne

**Pull request merged**
