### PR TITLE
keep sync with the immutable version of draft-js

### PR DESCRIPTION
**Pull request by lonelyclick**
A little anxious to use, will be able to merge and publish it ?

thank you very much

### CODE REVIEW

**Comment by lonelyclick** [comment]
#593

**Comment by nikgraf** [comment]
every plugin has it's own dependencies. can you extend the PR to update these dependencies as well? e.g. https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-counter-plugin/package.json#L38

**Comment by nikgraf** [comment]
@lonelyclick what do you mean by `A little anxious to use, will be able to merge and publish it ?`

**Comment by lonelyclick** [comment]
Please forgive me for my poor English, I want to use the new version quickly, so I want you to move faster release.

English : `A little anxious to use, will be able to merge and publish it ?` 
Chinese: `有点着急使用，能否麻烦合并并发布呢 ？`

so awkward...

**Comment by lonelyclick** [comment]
oh, build failure, please rebuild it

**Comment by nikgraf** [comment]
cool, thx for your help here!

**Pull request merged**
