### PR TITLE
Remove  to prevent react-unknown-props warning

### PR DESCRIPTION
**Pull request by aunsuwijak**
@nikgraf PR as we discussed in slack

### CODE REVIEW

**Comment by mjrussell** [comment]
@nikgraf I think mention has something similar which will warn in 15.2

**Comment by nikgraf** [comment]
@aunsuwijak instead of removing the props completely I propose to take out all the custom ones and then pass the `elementProps` down to the Anchor element. See how it's done here: https://github.com/draft-js-plugins/draft-js-plugins/pull/367/files

**Comment by aunsuwijak** [comment]
@nikgraf That solution looks better, I'll update this one soon.

**Comment by aunsuwijak** [comment]
@nikgraf After discussed with some other guy, I still not sure do we really need to take out unused props into variables.

**Comment by nikgraf** [comment]
@aunsuwijak any particular suggestion? I was thinking about using lodash's omit, but then that would need we need lodash as another dependency.

**Comment by nikgraf** [comment]
I'm closing this one as we solved all the react-unkown-props warnings.

**Pull request closed without merging**
