### PR TITLE
Move react to `peerDependencies`

### PR DESCRIPTION
**Pull request by sugarshin**
Hi,

Please check.

ref: https://github.com/draft-js-plugins/draft-js-plugins/issues/549

### CODE REVIEW

**Comment by nikgraf** [comment]
@sugarshin so sorry, but can you re-do the PR? I merged some other changes and split up a plugin into two.

**Comment by sugarshin** [comment]
@nikgraf I already push. Could you check this ?

**Comment by nikgraf** [comment]
hmmmm, should we add this to every changelog? If people didn't have React in their dependencies npm would throw an error, correct?

**Comment by sugarshin** [comment]
I think that as a behavior of a library that depends on React it is correct.

**Pull request merged**
